services:
  db:
    image: postgres:16
    container_name: smartaccount_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smartaccount
    ports:
      - "5433:5432"
    

    volumes:
      - smartaccount_pgdata:/var/lib/postgresql/data

volumes:
  smartaccount_pgdata:
